name = "twitter-video-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
# 在这里设置你的 Telegram Bot Token
# BOT_TOKEN = "your_bot_token_here"

# 推荐使用 secrets 管理敏感信息
# wrangler secret put BOT_TOKEN